cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false
#    credentials:
#      accessKey: ABC
#      secretKey: XYZ

sqs:
  orderEventQueue: order-event-queue

s3:
  orderEventBucket: order-event-bucket
